language: go

go:
  - tip

install:
  - go get golang.org/x/net/ipv4
  - go get github.com/udhos/netlink
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/unused/cmd/unused
  - go get honnef.co/go/simple/cmd/gosimple

script:
  - find $TRAVIS_BUILD_DIR -type d
  - go install github.com/udhos/nexthop/rib-old
  - go install github.com/udhos/nexthop/rib
  - go install github.com/udhos/nexthop/rip
  - go install github.com/udhos/nexthop/bgp
  - go install github.com/udhos/nexthop/tools/rip-query
  - go test addr bgp cli command netorder rip sock
