language: go

go:
  - tip

install:
  - go get golang.org/x/net/ipv4
  - go get github.com/udhos/netlink
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/unused/cmd/unused
  - go get honnef.co/go/simple/cmd/gosimple

script:
  - go install rib-old rib rip bgp tools/rip-query
  - go test addr bgp cli command netorder rip sock
