language: go

go:
  - tip

sudo: required

install:
  - go get golang.org/x/net/ipv4
  - go get github.com/udhos/netlink
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/unused/cmd/unused
  - go get honnef.co/go/simple/cmd/gosimple

script:
  - export NHPATH=github.com/udhos/nexthop
  - go install github.com/udhos/nexthop/rib-old
  - go install github.com/udhos/nexthop/rib
  - go install github.com/udhos/nexthop/rip
  - go install github.com/udhos/nexthop/bgp
  - go install github.com/udhos/nexthop/tools/rip-query
  - go test github.com/udhos/nexthop/addr
  - go test github.com/udhos/nexthop/bgp
  - go test github.com/udhos/nexthop/cli
  - go test github.com/udhos/nexthop/command
  - go test github.com/udhos/nexthop/netorder
  - go test github.com/udhos/nexthop/rip
  - sudo GOPATH=$GOPATH /home/travis/.gimme/versions/go/bin/go test github.com/udhos/nexthop/sock
