language: go

go:
  - tip

install:
  - go get golang.org/x/net/ipv4
  - go get github.com/udhos/netlink
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/unused/cmd/unused
  - go get honnef.co/go/simple/cmd/gosimple

script:
  - #find $TRAVIS_BUILD_DIR -type d
  - export NH_SRC=github.com/udhos/nexthop/src
  - go install $NHSRC/rib-old
  - go install $NHSRC/rib
  - go install $NHSRC/rip
  - go install $NHSRC/bgp
  - go install $NHSRC/tools/rip-query
  - go test $NHSRC/addr 
  - go test $NHSRC/bgp
  - go test $NHSRC/cli
  - go test $NHSRC/command
  - go test $NHSRC/netorder
  - go test $NHSRC/rip
  - go test $NHSRC/sock
